<script type="text/javascript">
   jQuery(document).ready(function() {   
    jQuery("#slideRight").owlCarousel({
    pagination : true,
	navigation : false, // Show next and prev buttons
    slideSpeed : 300,
    paginationSpeed : 400,
	autoPlay : true,
    singleItem:true     
    // "singleItem:true" is a shortcut for:
    // items : 1,
    // itemsDesktop : false,
    // itemsDesktopSmall : false,
    // itemsTablet: false,
    // itemsMobile : false
     
    });
     
    });

	 
</script>
<div class="rightBanner block-banner block">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block-slide-right')->toHtml() ?>	
</div>  