<?php
//BY LAKSHMAN - to change product count changed the Table value [table : core_config_data], [config_id: 107]
    $config = Mage::getStoreConfig('mdloption/newproducts');
    $categoryId = $config['newItemId'];
	$cObj = Mage::getModel('catalog/category')->load($categoryId);
//var_dump($cObj);
	$visibility = array(
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
        );
	$productObj = $cObj->getProductCollection()->addAttributeToFilter('visibility', $visibility)->getData();

//function to short array -by lakshman
function array_sort($array, $on, $order=SORT_ASC)
{
    $new_array = array();
    $sortable_array = array();

    if (count($array) > 0) {
        foreach ($array as $k => $v) {
            if (is_array($v)) {
                foreach ($v as $k2 => $v2) {
                    if ($k2 == $on) {
                        $sortable_array[$k] = $v2;
                    }
                }
            } else {
                $sortable_array[$k] = $v;
            }
        }

        switch ($order) {
            case SORT_ASC:
                asort($sortable_array);
                break;
            case SORT_DESC:
                arsort($sortable_array);
                break;
        }

        foreach ($sortable_array as $k => $v) {
            $new_array[$k] = $array[$k];
        }
    }

    return $new_array;
}

$newproductslist = array_sort($productObj, 'entity_id', SORT_DESC);

    $_helper = $this->helper('catalog/output');

?>
<?php if($config['newProductS']):?>
<?php if(count($productObj)<=0): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products home-new-product-section rowMin">
  <?php if($config['rowPro']=='1'):?>
  <?php $itemwidth = 'span6'; $proCount = '2';?>
  <?php elseif ($config['rowPro']=='2'):?>
  <?php $itemwidth = 'span4';  $proCount = '3'; ?>
  <?php elseif ($config['rowPro']=='3'):?>
  <?php $itemwidth = 'span3';  $proCount = '4'; ?>
  <?php elseif ($config['rowPro']=='4'):?>
  <?php $itemwidth = 'span2' ;  $proCount = '6'; ?>
  <?php endif; ?>
  <?php
      $eachRowProd = $proCount; // each row products
	  $productObj = array_slice($newproductslist,0, $config['newItem']);
	  $productObj1  = array_chunk($newproductslist, $eachRowProd);
	 ?>
  <?php foreach($productObj1 as $productObj): ?>
  <?php if($config['flip_view']==1 && $config['new_flip_view_style']==2):?>
	     <?php $flipviewStyleN='flipView2'; ?>
	<?php endif; ?>
  <ul class="newProducts itemPro item<?php echo $config['rowPro'];?>">
    <?php foreach($productObj as $_productData): ?>
    <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
    <li class="item <?php echo $itemwidth; ?> <?php if($config['itemviewbox']==1):?>secondViewInner<?php endif; ?>"> 
      

      <div class="new-inner">
        <div class="itemInner sec-view-inner <?php echo $flipviewStyleN; ?>">
          <div class="badge">
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
          </div>
          <?php if($config['newItem_quick_view']==1):?>
          <?php endif; ?>
          <?php if($config['flip_view']==1):?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  /> <span class="back-img"><img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(250,300); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" /></span> </a>
          <?php else: ?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a>
          <?php endif; ?>
          <span class="btn-eye">
          <?php if($config['newItem_quick_view']==1):?>
          <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i><?php echo $this->__('Quick View')?></a>

          <?php endif; ?>
          </span> </div>

      </div>

    </li>
    <?php endforeach ?>
  </ul>
  <?php endforeach ?>
</div>
<?php endif; ?>
<?php endif; ?>
