<?php
    $_productCollection=$this->getLoadedProductCollection();
    $columnCount = mdlList('column_count');
    $this->setColumnCount($columnCount);
    $_helper = $this->helper('catalog/output');   
?>
<!--code start-->

<!--If products are not available-->

<?php if(!$_productCollection->count()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<!--condition end-->

<?php else: ?>
<?php $config = Mage::getStoreConfig('mdloption/item_view');?>
<div class="category-products f-block"> 
  <?php if($config['flip_view']==1 && $config['list_flip_view_style']==2):?>
	 <?php $flipviewStyleL='flipView2'; ?>
<?php endif; ?>
  <!--Toolbar--> 
  
  <?php echo $this->getToolbarHtml() ?> 
  
  <!--end Toolbar--> 
  
  <!--List View-->
  
  <?php if($this->getMode()!='grid'): ?>
  <?php $_iterator = 0; ?>
  <?php $imgSize = 192; ?>
  <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      <div class="itemInner span3 <?php echo $flipviewStyleL; ?>"> 
        
        <!--Quick view-->
        
        <?php if($config['itemviewbox_quick_view']==1):?>
        <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
        <?php endif; ?>
        
        <!--end Quick view--> 
        
        <!--badge-->
        
        <div class="badge">
          <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
          <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
        </div>
        
        <!--end badge--> 
        
        <!--Flip View-->
        
        <?php if($config['flip_view']==1):?>
        <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> <span class="back-img"><img class="hoverImg" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(250,300); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" /></span> </a> 
        
        <!--end Flip view-->
        
        <?php else:?>
        
        <!--Default view--> 
        
        <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" /> </a>
        <?php endif;?>
      </div>
      
      <!--end default view-->
      
      <?php // Product description ?>
      <div class="product-shop span9">
        <div class="f-fix">
          <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
          <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
          
          <!--Price-->
          
          <div class="f-block"><?php echo $this->getPriceHtml($_product, true) ?></div>
          
          <!--end price--> 
          
          <!--review--> 
          
          <?php echo $this->getReviewsSummaryHtml($_product, false, true)?> 
          
          <!--end review--> 
          
          <!--Description-->
          
          <div class="desc std"> <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a> </div>
          
          <!-- end Description-->
          
          <div class="bottomBox"> 
            
            <!-- if quick view is available -->
            
            <?php if($config['itemviewbox_quick_view']==1):?>
            <?php if($_product->isSaleable()): ?>
            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
            <button rel="tooltip" data-placement="top" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i>
            <?php //echo $this->__('Add to Cart') ?>
            </span></button>
            <?php else: ?>
            <a rel="tooltip" data-placement="top" title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-shopping-cart"></i>
            <?php //echo $this->__('Add to Cart') ?>
            </a>
            <?php endif; ?>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <?php else: ?>
            <?php if($_product->isSaleable()): ?>
            <button rel="tooltip" data-placement="top" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <?php endif; ?>
            
            <!-- end quick view --> 
            
            <!--Add to-->
            
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><i class="fa fa-heart"></i></a>
            <?php endif; ?>
            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
            <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="compareR"><i class="fa fa-exchange"></i></a>
            <?php endif; ?>
            
            <!--end add to--> 
            
          </div>
        </div>
      </div>
    </li>
    <?php endforeach; ?>
  </ol>
  <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
  <?php else: ?>
  
  <!--end List View-->
  
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php 

    

        $_columnCount = $this->getColumnCount(); 

        

        if($_columnCount == 4){

			$listWidth = 'span3';

            $imgSize = 155;

        }elseif($_columnCount == 3){

			$listWidth = 'span4';

            $imgSize = 245;

      } 

    ?>
  
  <!--Grid view-->
  
  <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid itemPro">
    <?php endif ?>
    <li class="item <?php if(($i-1)%$_columnCount==0): ?> first <?php elseif($i%$_columnCount==0): ?> last <?php endif; ?><?php echo $listWidth ?> <?php if($config['itemviewbox']==1):?>secondViewInner<?php endif; ?>">
      <div class="grid-inner"> 
        
        <!--Item first view-->
        
        <?php if($config['itemviewbox']==0):?>
        <div class="itemInner <?php echo $flipviewStyleL; ?>"> 
          
          <!--Quick view-->
          
          <?php if($config['itemviewbox_quick_view']==1):?>
          <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
          <?php endif; ?>
          
          <!--end Quick view--> 
          
          <!--badge-->
          
          <div class="badge">
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
          </div>
          
          <!--end badge--> 
          
          <!--flip view-->
          
          <?php if($config['flip_view']==1):?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img  class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> <span class="back-img"> <img class="hoverImg" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(250,300); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" /></span> </a>
          <?php else:?>
          
          <!--end flip view--> 
          
          <!--Image default view--> 
          
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a>
          <?php endif;?>
          
          <!--end default view--> 
          
        </div>
        <div class="bottomBox">
          <h2 class="product-name"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
          <?php echo $this->getPriceHtml($_product, true, '-right') ?>
          <?php if($config['itemviewbox_quick_view']==1):?>
          <?php if($_product->isSaleable()): ?>
          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
          <button rel="tooltip" data-placement="top" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i>
          <?php //echo $this->__('Add to Cart') ?>
          </span></span></button>
          <?php else: ?>
          <a rel="tooltip" data-placement="top" title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-shopping-cart"></i>
          <?php //echo $this->__('Add to Cart') ?>
          </a>
          <?php endif; ?>
          <?php else: ?>
          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
          <?php endif; ?>
          <?php else: ?>
          <?php if($_product->isSaleable()): ?>
          <button rel="tooltip" data-placement="top" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php //echo $this->__('Add to Cart') ?></span></span></button>
          <?php else: ?>
          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
          <?php endif; ?>
          <?php endif; ?>
          <?php if ($this->helper('wishlist')->isAllow()) : ?>
          <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><i class="fa fa-heart"></i></a>
          <?php endif; ?>
          <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
          <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="compareR"><i class="fa fa-exchange"></i></a>
          <?php endif; ?>
        </div>
        
        <!--end item first view--> 
        
        <!--second view-->
        
        <?php else: ?>
        <div class="itemInner sec-view-inner <?php echo $flipviewStyleL; ?>"> 
          
          <!--badge-->
          
          <div class="badge">
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
          </div>
          
          <!--end badge--> 
          
          <!--flip view-->
          
          <?php if($config['flip_view']==1):?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img class="front-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><span class="back-img"><img class="hoverImg" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(250,300); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" /></span></a>
          <?php else:?>
          
          <!--end flip view--> 
          
          <!--Image default view--> 
          
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a>
          <?php endif;?>
          
          <!--end default view--> 
          
          <span class="btn-eye">
          <?php if($config['itemviewbox_quick_view']==1):?>
          <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i><?php echo $this->__('Quick View')?></a>
          <?php endif; ?>
          </span> </div>
        <div class="bottomBox bottomBox2">
          <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
          <?php echo $this->getPriceHtml($_product, true, '-right') ?>
          <div class="buttonox-center">
            <?php if($config['itemviewbox_quick_view']==1):?>
            <?php if($_product->isSaleable()): ?>
            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
            <button rel="tooltip" data-placement="top" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
            <?php else: ?>
            <a rel="tooltip" data-placement="top" title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></a>
            <?php endif; ?>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <?php else: ?>
            <?php if($_product->isSaleable()): ?>
            <p>
              <button rel="tooltip" data-placement="top" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></button>
            </p>
            <?php else: ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <?php endif; ?>
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <?php endif; ?>
          </div>
          <?php if ($this->helper('wishlist')->isAllow()) : ?>
          <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><i class="fa fa-heart"></i> <?php echo $this->__('Add to Wishlist') ?></a>
          <?php endif; ?>
          <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
          <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="compareR"><i class="fa fa-exchange"></i> <?php echo $this->__('Add to Compare') ?></a>
          <?php endif; ?>
        </div>
        <?php endif; ?>
        
        <!--end second view--> 
        
      </div>
    </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
  </ul>
  <?php endif ?>
  <?php endforeach ?>
  <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
  <?php endif; ?>
  <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
</div>
<?php endif; ?>
<script type="text/javascript">

	jQuery(window).scroll(function(){

	    jQuery("[rel=tooltip]").tooltip();

	});

</script> 
