<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    $gallery = '<div class="more-views">';
    $gallery .= '<ul>';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(100) . '"  alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
}
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div class="product-cover <?php if (!isset($gallery)): ?> no-thumb-view <?php endif; ?>">
<div class="f-block">
<div class="badge">			
     <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
     <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
</div>
<p class="product-image product-image-zoom">
<a class="zoomBtn" rel="example_group" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>"><i class="fa fa-search-plus"></i></a>	
    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom ajax" id="cloudZoom">
    <?php
        $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a>
</p>
</div>
</div>
    <?php if(isset($gallery)): ?>
       <div class="thumbbox"><?php echo $gallery; ?></div>
    <?php endif; ?>
<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>

<?php endif; ?>

<?php $config = Mage::getStoreConfig('mdloption/product-type-option'); ?>
<script type="text/javascript">
	jQuery(document).ready(function(){
			jQuery('.cloud-zoom-gallery').click(function(){
				var srcBox = jQuery('#image').attr('src');
				jQuery('.zoomBtn').attr("href", srcBox);
			});
			
		jQuery('.more-views').jcarousel({
			start: 1,
			scroll:1,
	<?php if($config['product-view-option']==3):?>
			vertical:true,
	<?php endif; ?>
			wrap: 'circular'
		});
	});
</script>

